"""Count joint hardware from the mechanical operations, with measured stacks."""
import json
from collections import Counter
from pathlib import Path
OUT=Path(__file__).resolve().parents[2]/'hardware/printed-parts/fixtures/gun-positioner'
rows=[]
def joint(name,fastener,quantity,nut,washer,grip,operation,instances=()):
 rows.append(dict(joint=name,fastener=fastener,quantity=quantity,nut_or_thread=nut,flat_washers_per_fastener=washer,grip_basis=grip,operation=operation,instances=list(instances)))
joint('rails-to-bed','M3x20',48,'M3 locking nut',2,'Rail foot4 +plate6.35 +washers1 +nut4 =15.35 mm; 4.65 mm protrusion. Transfer actual rail holes.','XYZ rails',[f'{a}-rail-{s}' for a in('x','y','z') for s in(-1,1)])
joint('blocks-to-carriage','M5x16',48,'purchased M5 tapped block',1,'Plate6.35 +washer1 leaves8.65 mm engagement in verified10 mm depth;1.35 mm bottom margin.','XYZ blocks',[f'{a}-block-{s}-{p}' for a in('x','y','z') for s in(-1,1) for p in(-1,1)])
joint('x-to-y-deck-spacers','M5x70',4,'M5 locking nut',2,'Metal spacer40 +two plates12.7 +washers2 +nut5 =59.7 mm;10.3 mm protrusion.','XYZ deck stack')
joint('shaft-hub-mount','M5x45',28,'M5 locking nut',2,'Hub25 +plate6.35 +washers2 +nut5 =38.35 mm;6.65 mm protrusion.','Gimbal hubs')
joint('shaft-two-station-split-clamps','M4x50 grade12.9',14,'M4 locking nut',2,'Hub38.1 +washers2 +nut5 =45.1 mm;4.9 mm protrusion. Two clamp bores per hub, Y16/Z6 and19; plain shaft has no cross hole. Measured proof in both signs: pitch drive/negative pitch output30-32.5 Nm; other hubs25.2-27.5 Nm.25 in-lb cam-over setting, absolute upper3 Nm.','Gimbal hubs')
joint('gimbal-pillow-bearings','M6x25',12,'M6 locking nut',2,'Housing foot6 +plate6.35 +washers2 +nut6 =20.35 mm;4.65 mm protrusion.','Gimbal bearings')
joint('fixed-screw-radial-bearings','M4x35',12,'M4 locking nut',2,'Foot5 +riser11.35 +floor6.35 +washers2 +nut5 =29.70 mm;5.30 mm protrusion. Transfer actual42 mm centers and finish riser from actual center height. M4 washers at least10 OD bridge8 mm tube bore.','Drive cartridges')
joint('floating-screw-radial-bearings','M4x30',6,'M4 locking nut',2,'Foot5 +riser5 +bed6.35 +washers2 +nut5 =23.35 mm;6.65 mm protrusion. No axial nut outside bearing.','XYZ floating bearings')
joint('motor-face','M3x12',24,'motor M3 tapped thread',1,'Printed plate8 +washer0.5 leaves3.5 mm engagement. Verify motor thread depth and no bottoming.','All six drives')
joint('pulley-to-fixed-nut','M3x20',24,'M3 locking nut',2,'Pulley9.4 +flange3.5 +washers1 +nut4 =17.9 mm;2.1 mm protrusion.','All six drives')
joint('single-moving-nut-to-face','M3x20',24,'M3 locking nut',2,'Plate6.35 +flange3.5 +washers1 +nut4 =14.85 mm;5.15 mm protrusion. Tangential slots use large metal washers.','All six force links')
joint('inner-nut-frame-and-outer-cage-ties','M5x90',48,'M5 locking nut',2,'Angular cage outer span74.4244, XYZ70.9360 +washers2 +nut5 =81.4244/77.9360 mm;8.5756/12.0640 mm protrusion. Plastic locator is excluded from the clamped stack.','All six force links')
joint('main-force-boss-pairs','M3x30',48,'M3 locking nut',2,'Two bosses14.7 +shuttle6.35 +washers1 +nut4 =26.05 mm;3.95 mm protrusion.','All six force links')
joint('crash-force-boss-pairs','M3x30',8,'M3 locking nut',2,'Two bosses14.7 +shuttle6.35 +washers1 +nut4 =26.05 mm;3.95 mm protrusion.','Crash axial pods')
joint('main-smooth-guide-bolts','M8x90 partly threaded grade8.8',12,'M8 locking nut',2,'Smooth shank must span the entire bronze bushing through its +/-1 mm movement. Angular outer span74.4244 +washers3 +nut8 =85.4244 mm;4.5756 mm protrusion. Inspect actual DIN931 shank length before use.','All six force links')
joint('unbraked-thrust-bulkhead-posts','M6x25',12,'M6 locking nut',2,'Metal angle3.175 +bulkhead6.35 +washers2 +nut6 =17.525 mm;7.475 mm protrusion. M6 posts share the mounting duty; no overlapping M5 holes.','X/Y/yaw cartridges')
joint('retained-thrust-posts','M6x80 finished72.5',12,'three M6 nuts per post',2,'Angle and bulkhead clamp to first nut; two further jam nuts locate spring seat. Finish under-head length72.5 mm and deburr before assembly. At least two threads beyond last nut.','Z/pitch/roll cartridges')
joint('friction-washer-anti-rotation','M3x50',6,'two M3 nuts per guide bolt',1,'Guide bolts fixed to seat; washers slide and tilt freely. Pins carry only washer torque. Confirm no coil, brass body or shoulder interference.','Z/pitch/roll cartridges')
joint('hinge-smooth-stubs','M8x50 partly threaded grade8.8',12,'M8 locking nut',2,'Smooth shank covers bearing5 mm. Add metal inner-race spacer stack to thread start; clamp ear and inner race without clamping outer race. Actual bearing/washer/spacer grip is finished from supplied bolt shank.','Angular clevises')
joint('hinge-bearing-retainers','M3x14',24,'M3 locking nut',1,'Metal cheek6.35 +large steel washer1 +nut4 =11.35 mm;2.65 mm protrusion. Large washer retains only bearing flange.','Angular clevises')
joint('angular-base-cheek-to-web','M5x20',12,'M5 locking nut',2,'Two metal plates12.7 +washers2 +nut5 =19.7 mm. Use M5x25 at this two-plate joint to preserve two full threads.','Angular base webs')
# Correct the explicitly checked two-plate stack before counting purchases.
rows[-1]['fastener']='M5x25';rows[-1]['grip_basis']='Two plates12.7 +washers2 +nut5 =19.7 mm;5.3 mm protrusion.'
joint('pitch-web-to-yaw-side','M5x90',4,'M5 locking nut',2,'Webs12.7 +side6.35 +spacers31.35/28.65 +washers2 +nut5 =86.05 mm;3.95 mm protrusion.','Pitch base webs')
joint('roll-foot-through-anchor','M5x35',4,'M5 locking nut',2,'Crossbar6.35 +anchor6.35 +spacer6.95 +foot6.35 +washers2 +nut5 =33.0 mm;2.0 mm protrusion.','Roll base anchor')
joint('angular-output-bridge-to-lever','M5x25',12,'M5 locking nut',2,'Two plates12.7 +washers2 +nut5 =19.7 mm;5.3 mm protrusion.','Angular outputs')
joint('angular-output-cheek-cross-ties','M5x80',6,'M5 locking nut',2,'Outer cheek span66.35 +washers2 +nut5 =73.35 mm;6.65 mm protrusion. Four23.65 mm metal spacers per angular output.','Angular outputs')
angle_alloc=[('yaw-head',3),('yaw-crossbar-to-sides',4),('pitch-bearing-feet-to-yaw-sides',4),('pitch-crossbars-to-sides',8),('roll-cradle-back-to-sides',4),('motor-supports',24),('bulkhead-supports',36),('XYZ-shuttle-outputs',6),('angular-inner-ear-joints',24),('yaw-and-roll-base-web-anchors',8),('crash-fixed-crossbars',8),('crash-shuttle-to-output-walls',4),('crash-walls-to-carriers',4),('crash-carriers-to-magnetic-back',2),('released-tray-to-back',2),('powered-test-fork',4),('nozzle-test-fork',4)]
assert sum(q for _,q in angle_alloc)==149
joint('metal-angle-joints','M5x20',266,'M5 locking nut',2,'Angle3.175 +metal plate6.35 +washers2 +nut5 =16.525 mm;3.475 mm protrusion. Motor print8 gives18.175 mm;1.825 mm protrusion. Twenty-four bulkhead angle legs use shared M6 posts; twelve foot legs use separately counted M5x25. Four rear nozzle angles have an additional hole per leg.','Named angle allocations',[f'{name}-angle-{i+1}' for name,q in angle_alloc for i in range(q)])
joint('drive-extension-to-bed','M5x20',6,'M5 locking nut',2,'Two plates12.7 +washers2 +nut5 =19.7 mm. Use M5x25 to preserve two full threads.','XYZ fixed supports');rows[-1]['fastener']='M5x25';rows[-1]['grip_basis']='Two plates12.7 +washers2 +nut5 =19.7 mm;5.3 mm protrusion.'
joint('lower-jaws-to-released-tray','M5x20',4,'M5 locking nut',2,'Two plates12.7 +washers2 +nut5 =19.7 mm. Use M5x25; lower-jaw attachment holes atY+/-32, clamp bolts separate atY+/-56.','Gun release tray');rows[-1]['fastener']='M5x25';rows[-1]['grip_basis']='Two plates12.7 +washers2 +nut5 =19.7 mm;5.3 mm protrusion.'
joint('gun-clamp-and-temporary-test-clamp','M5x80',6,'two M5 nuts per fastener',2,'Four working jaw bolts and two temporary load-clamp bolts. Adjustable shell gap; maintain two full threads past outer lock nut without crushing gun or pad.','Gun clamp and crash force fixture')
joint('switch-body-to-print','M3x20',56,'M3 locking nut',1,'Actual switch body and bracket measured on receipt. Nominal body5 +print6 +washer0.5 +nut4 =15.5 mm;4.5 mm protrusion. Never clamp or obstruct lever travel.','Twenty-eight switches')
joint('switch-bracket-to-metal','M6x25',28,'M6 locking nut',2,'Print6 +plate6.35 +washers2 +nut6 =20.35 mm;4.65 mm protrusion. Printed slot provides adjustment; metal backing takes reaction.','Twenty-eight switches')
joint('overload-cam-flags','M5x25',16,'M5 locking nut',2,'Two plates12.7 +washers2 +nut5 =19.7 mm;5.3 mm protrusion.','Six main links and two crash axial contacts')
joint('belt-guards','M3x25',12,'M3 locking nut',2,'Shield2 +bulkhead6.35 +spacer7 +top angle3.175 +washers1 +nut4 =23.525 mm;1.475 mm protrusion, exceeding two0.5 mm M3 threads. Registered holes are bulkhead(+/-5,13), guardY-7; transfer-drill matching top-angle passages.','All six drives')
joint('linear-stop-face-and-foot','M6x25',24,'M6 locking nut',2,'Source angle6.35 +plate6.35 +washers2 +nut6 =20.7 mm;4.3 mm protrusion. Transfer purchased angle foot after finish.','XYZ metal stops')
joint('angular-stops-to-web','M5x25',12,'M5 locking nut',2,'Two metal plates12.7 +washers2 +nut5 =19.7 mm;5.3 mm protrusion.','Angular metal stops')
joint('4040-corner-bracket-fasteners','M8x16',76,'slot8 M8 T-nut',1,'38 purchased B0BS6MG9D5 40-series corner brackets, two included matched M8 screws per bracket. Measure supplied stack and T-nut reach; no bottoming.','Common frame, mast, head and boom')
joint('4040-plate-fasteners','M6x16',12,'slot8 M6 T-nut',1,'Plate6.35 +washer1 leaves8.65 mm reach; swivel bracket uses measured stack. Verify slot seating and screw tip clearance.','X bed4, Z bed4, head adapter2, diagonal2')
joint('bench-frame-and-fiber-anchors','M8x75',8,'M8 locking nut',2,'Four station and four independent boom bench anchors. Actual bench thickness must leave two full threads; use purchased bracket and metal washer backing.','Bench installation')
joint('fiber-swivel-and-torque-wheel-axles','M8x50 partly threaded grade8.8',3,'M8 locking nut',2,'Two swivel bearings and one temporary redirect. Smooth shank covers7 mm608 inner race; metal spacers carry clamp load without binding outer race.','Fiber support and torque test')
joint('crash-cage-ties','M3x100',8,'M3 locking nut',2,'Nominal pod outer span81.4081 +washers1 +nut4 =86.4081 mm;13.5919 mm protrusion. Finish metal spacers by measured spring grading; keep captured center8.35 mm.','Two crash pods')
joint('crash-lower-guide-blocks','M3x40',8,'M3 locking nut',2,'Square block25.4 +wall6.35 +washers1 +nut4 =36.75 mm;3.25 mm protrusion. Side holesZ+/-8 mm clear the12.1 mm rod-guide bore.','Two crash output walls')
joint('crash-cup-magnets','M5x25 countersunk',3,'M5 locking nut',1,'Cup7.7 +plate6.35 +shim<=3 +washer1 +nut5 =23.05 mm;1.95 mm protrusion. Verify actual countersink flushness and two0.8 mm threads. Use machine screws.','Three cup magnets')
joint('crash-cup-strikers','M5x16',3,'M5 locking nut',1,'Steel washer2 +plate6.35 +washer1 +nut5 =14.35 mm;1.65 mm protrusion, two0.8 mm threads.','Three magnetic strikers')
joint('crash-ball-steel-backing','M3x20',6,'M3 locking nut',1,'Steel backing2 +plate6.35 +washer0.5 +nut4 =12.85 mm;7.15 mm protrusion. Ball only locates with retaining compound; working compression seats on steel6 mm aperture.','Three ball seats')
joint('V-seat-metal-keepers','M3x25',12,'M3 locking nut',2,'Backplate6.35 +metal stand-off4 +keeper6.35 +washers1 +nut4 =21.7 mm;3.3 mm protrusion. Keepers are outside ball contact region.','Six hardened-dowel end keepers')
joint('torque-tool-service-bolts','M3x20',4,'reuse rotating-flange M3 locking nuts',2,'Temporary balanced lever6.35 +flange3.5 +washers1 +nut4 =14.85 mm;5.15 mm protrusion. Reuse four pulley bolts; these are not additional purchase consumption.','Unpowered service test')
joint('test-fork-bridge-and-platen','M5x25',12,'M5 locking nut',2,'Two plates12.7 +washers2 +nut5 =19.7 mm;5.3 mm protrusion. Temporary fixtures react only through intended fixed or output side, never both.','Static and powered force fixtures')
joint('thrust-foot-angle-to-floor','M5x25',12,'M5 locking nut',2,'Angle3.175 +bed or pad6.35 +floor6.35 +washers2 +nut5 =22.875 mm;2.125 mm protrusion.','All six drive feet')
joint('fiber-fixed-base-to-beam','M6x30',8,'slot8 M6 T-nut',1,'Printed base10 +metal spacer10 +washer1 leaves9 mm T-nut reach. Verify actual seating and no bottoming. Metal spacer carries clamp load; grade base stability with supported cable.','Two fiber swivel bases')
joint('fiber-and-redirect-outer-race-caps','M3x20',6,'M3 locking nut',2,'Saddle center10 +cap2 +washers1 +nut4 =17 mm;3 mm protrusion. Cap clears inner race and fixed axle.','Two fiber swivel saddles and one temporary redirect')
joint('nozzle-test-cord-stud','M6x40 grade8.8',1,'two M6 nuts per fastener',2,'Cross-hole3.5 mm is5 mm from under-head. Two nuts lock both sides of the6.35 mm bridge; eye position is measured at virtual X200 datum.','Nozzle force fixture')
joint('force-gauge-rear-mount','M4x25 finish-to-depth',4,'force gauge M4 tapped socket',1,'Use included screws if actual plate6.35 +washer1 leaves required engagement without bottoming. Otherwise finish four allocated spare M4x25 to measured socket depth, at least4 mm engagement unless manufacturer requires more.','70x110 force-gauge backing')
joint('installed-Z-gauge-column-brackets','M8x16',4,'slot8 M8 T-nut',1,'Two included40-series bracket pairs brace temporary500 mm column independently to station. Reuse kit spares; separate from38 permanent corners.','Installed Z load test')
joint('installed-Z-gauge-back-to-column','M6x25',2,'slot8 M6 T-nut',1,'Metal6.35 +spacer10 +washer1 leaves7.65 mm T-nut reach. Rear gauge screw heads remain clear; verify no bottoming.','Installed Z load test')
joint('installed-Z-gauge-jack-angle-to-column','M6x16',2,'slot8 M6 T-nut',1,'Metal angle6.35 +washer1 leaves8.65 mm reach; jack foot sits60 mm below gauge-back lower edge.','Installed Z load test')
joint('installed-Z-gauge-jack-feed','M6x80',1,'two M6 nuts per fastener',2,'Fully threaded metal feed screw reacts into two metal nuts on6.35 mm angle. Hold lower nut with wrench while feeding at most1/12 turn; upper nut locks the setting.','Installed Z load test')
joint('shaft-end-positive-retainers','M5x12',8,'M5 tapped shaft end',1,'2 mm steel washer +0.8 mm flat washer leaves9.2 mm engagement, measured usable full thread10 mm/pilot16 mm. Require at least8 mm engagement and0.8 mm bottom margin.','All four gimbal shafts')
joint('proof-force-gauge-rear-mount','M4x25 finish-to-depth',4,'force gauge M4 tapped socket',2,'Plate6.35 +spacer7 +two large washers2 =15.35 mm before engagement. Finish a separate four-screw set to measured socket depth with at least4 mm engagement and no bottoming; never reuse the shorter normal gauge set.','Torque and axial capture proof fixtures')
joint('hub-proof-quill-cap-and-saddle','M5x25',3,'M5 locking nut',2,'Two cap bolts: metal12.7 +washers1.6 +nut5 =19.3 mm,5.7 mm protrusion. One saddle cross tie: same12.7 mm metal stack.','Hub proof fixture')
joint('hub-proof-KP001-risers','M6x40 grade12.9',4,'M6 locking nut',2,'Foot6 +riser10 +plate6.35 +washers2 +nut6 =30.35 mm,9.65 mm protrusion. Actual source boltgrade12.9 meets requiredminimum8.8.','Hub proof fixture')
joint('hub-proof-foot-to-horizontal-column','M8x16',4,'slot8 M8 T-nut',1,'6.35 mm plate +1.5 mm washer leaves8.15 mm reach. Four spare kit pairs allocated, two used in canonical single-bearing proof. Verify actual engagement/no bottoming.','Hub proof fixture')
joint('hub-proof-reused-service-joints','M5x20',2,'M5 locking nut',2,'Reuse two powered-fork angle joints in the load saddle. Never assemble both fixtures simultaneously.','Hub proof fixture');rows[-1]['reuse_from']='powered-test-fork'
joint('axial-proof-gauge-guides','M6x25',2,'slot8 M6 T-nut',1,'Metal6.35 +spacer9.825 +washer1 leaves7.825 mm reach. Maintain measured sliding clearance; washer must not clamp the moving gauge back.','Axial capture proof')
joint('axial-proof-positive-gauge-interface','M6x16',1,'steel M6x1 coupling nut',1,'Bridge6.35 +washer1 leaves8.65 mm engagement in20 mm steel coupler. Gauge engages at least6 mm; measured ends do not bottom.','Axial capture proof')
joint('axial-proof-reused-interface-joints','M5x80',4,'M5 locking nut',2,'Reuse four angular output ties temporarily through actual output plate6.35 +hub25 +interface6.35. No gun is mounted during proof.','Axial capture proof');rows[-1]['reuse_from']='angular-output-cheek-cross-ties'
joint('axial-proof-reused-bridge-ties','M3x100',4,'M3 locking nut',2,'Reuse four crash ties with75 mm tube +two6.35 plates +washers1 +nut4 =92.7 mm;7.3 mm protrusion. Set0.2 mm locating slack.','Axial capture proof');rows[-1]['reuse_from']='crash-cage-ties'
joint('axial-proof-reused-catch-joints','M5x35',2,'M5 locking nut',2,'Reuse two roll-foot joints. Two plates12.7 +spacer7.85 +washers1.6 +nut5 =27.15 mm;7.85 mm protrusion.','Axial capture proof');rows[-1]['reuse_from']='roll-foot-through-anchor'
joint('axial-proof-reused-jack','M6x16',2,'slot8 M6 T-nut',1,'Temporarily transfer installed Z jack angle and fully threaded M6x80 feed assembly. Do not operate both fixtures at once.','Axial capture proof');rows[-1]['reuse_from']='installed-Z-gauge-jack-angle-to-column'
joint('hub-proof-reused-vise-anchors','M8x75',2,'M8 locking nut',2,'Temporarily transfer two bench anchors while no assembled gun/load is on the station. Mount through factory vise slots and check actual grip/two threads.','Hub proof fixture');rows[-1]['reuse_from']='station-bench-anchors'
(OUT/'fasteners.json').write_text(json.dumps(rows,indent=2)+'\n')
(OUT/'joint-allocations.json').write_text(json.dumps({'metal_angle_25':dict(quantity=149,cut_length_mm=25.4,profile_mm=[25.4,25.4,3.175],operations=[dict(operation=n,quantity=q) for n,q in angle_alloc]),'4040_corner_brackets':dict(quantity=40,operations={'six_crossbeam_ends':24,'two_mast_feet':4,'head_column_and_beam':4,'fiber_bench_foot':4,'fiber_arm_to_post':2,'temporary_installed_Z_column':2})},indent=2)+'\n')
bolts=Counter();nuts=Counter();wash=Counter()
for r in rows:
 if r['joint']=='torque-tool-service-bolts' or r.get('reuse_from'):continue
 q=r['quantity'];f=r['fastener'];size=f.split('x')[0];bolts[f]+=q;wash[size]+=q*r['flat_washers_per_fastener']
 n=r['nut_or_thread']
 if 'locking nut' in n:nuts[size+' locking nut']+=q
 elif n=='three M6 nuts per post':nuts['M6 nut']+=3*q
 elif n=='two M3 nuts per guide bolt':nuts['M3 nut']+=2*q
 elif n=='two M5 nuts per fastener':nuts['M5 nut']+=2*q
 elif n=='slot8 M6 T-nut':nuts['M6 slot8 T-nut']+=q
 elif n=='slot8 M8 T-nut':nuts['M8 slot8 T-nut']+=q
 elif n=='two M6 nuts per fastener':nuts['M6 nut']+=2*q
 elif n=='steel M6x1 coupling nut':nuts['M6x1 coupling nut']+=q
summary={'scope':'Mechanism plus temporary fixtures; camera hardware remains in its own BOM. Counts are consumption, excluding purchase-pack rounding and included collar/motor/pinion screws.','bolts':dict(bolts),'nuts':dict(nuts),'flat_washers':dict(wash),'large_M3_washer_requirements':{'moving_nut_slots':{'quantity':48,'minimum_OD_mm':10,'maximum_ID_mm':3.4},'hinge_bearing_flange_retention':{'quantity':24,'minimum_OD_mm':12,'maximum_ID_mm':3.4,'thickness_mm':1},'scope':'These are subsets of the M3 washer total and need a separate large-OD source; ordinary7 mm M3 washers cannot substitute.'},'large_M4_riser_washers':{'quantity':36,'minimum_OD_mm':10,'maximum_ID_mm':4.5},'large_M4_proof_gauge_washers':{'quantity':8,'minimum_OD_mm':12,'maximum_ID_mm':4.5,'thickness_mm':1},'metal_M3_standoffs':{'belt_shield':{'quantity':12,'length_mm':7,'OD_mm':8,'ID_mm':6},'V_seat_keeper':{'quantity':12,'length_mm':4,'OD_mm':8,'ID_mm':6}},'other_washers':{'M10_ID10.5_OD20_x2mm':60,'M8_ID8.5_OD32_x1.5mm':28,'M12_ID13_OD37_x3mm':3,'M6_ID6_OD25_x2mm_carbon_steel':6,'M6_ID6_OD20_x2mm_304_shaft_end':8},'metal_angle_slices':149,'corner_brackets_4040':40}
(OUT/'hardware-counts.json').write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps(summary,indent=2))
