import { chromium } from 'playwright';
import fs from 'fs';
const exe='/opt/pw-browsers/chromium';
const b=await chromium.launch({executablePath: fs.existsSync(exe)?exe:undefined,args:['--no-sandbox']});
const p=await b.newPage();
p.on('requestfailed', r=>console.log('FAIL', r.url(), r.failure()?.errorText));
p.on('response', r=>{ if(/fonts\./.test(r.url())) console.log(r.status(), r.url()); });
await p.setContent(`<link rel=stylesheet href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@500;700&display=swap"><div style="font-family:'Zen Maru Gothic'">Cleaning 1:20</div>`);
await p.waitForTimeout(4000);
console.log(await p.evaluate(()=>document.fonts.size + ' faces; loaded=' + [...document.fonts].map(f=>f.family+':'+f.status).join(',')));
await b.close();
