// Generated by make_geometry.py from the mechanical geometry-check.json.
#pragma once
#include <array>
#include <cstdint>
namespace gun_positioner {
constexpr int32_t kCountsPerMm = 6400;
constexpr std::array<int32_t, 6> kMinCount = {-544000, -544000, -544000, -326307, -326307, -326307};
constexpr std::array<int32_t, 6> kMaxCount = {544000, 544000, 544000, 329471, 166782, 329471};
}
