#!/usr/bin/env python3
"""Bind firmware count limits to the mechanical package's canonical geometry."""
import argparse
import json
import math
from pathlib import Path

HERE = Path(__file__).resolve().parent
GEOMETRY = HERE.parents[1] / "hardware/printed-parts/fixtures/gun-positioner/geometry-check.json"
HEADER = HERE / "geometry_generated.h"

def render(path=GEOMETRY):
    geometry = json.loads(Path(path).read_text())
    pulses = geometry["nominal_motion"]["sixteen_microstep_command_pulses_per_mm"]
    if not float(pulses).is_integer() or pulses <= 0:
        raise ValueError("Integer positive pulses/mm required")
    lo, hi = geometry["linear_limits_mm"]["soft"]
    l0 = geometry["angular_actuator"]["L0_mm"]
    r = geometry["angular_actuator"]["r_mm"]
    limits = geometry["angular_limits_deg"]
    per_axis = limits.get("soft_by_axis", {})
    def length(deg):
        a = math.radians(deg)
        return math.sqrt(l0*l0 + 2*l0*r*math.sin(a) + 2*r*r*(1-math.cos(a)))
    angular_ranges = [per_axis.get(axis, limits["soft"]) for axis in ("yaw", "pitch", "roll")]
    lower = [math.ceil(lo * pulses)] * 3 + [math.ceil((length(v[0]) - l0) * pulses) for v in angular_ranges]
    upper = [math.floor(hi * pulses)] * 3 + [math.floor((length(v[1]) - l0) * pulses) for v in angular_ranges]
    return ("// Generated by make_geometry.py from the mechanical geometry-check.json.\n"
            "#pragma once\n#include <array>\n#include <cstdint>\nnamespace gun_positioner {\n"
            f"constexpr int32_t kCountsPerMm = {int(pulses)};\n"
            "constexpr std::array<int32_t, 6> kMinCount = {" + ", ".join(map(str, lower)) + "};\n"
            "constexpr std::array<int32_t, 6> kMaxCount = {" + ", ".join(map(str, upper)) + "};\n"
            "}\n")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--geometry", type=Path, default=GEOMETRY)
    parser.add_argument("--output", type=Path, default=HEADER)
    args = parser.parse_args()
    expected = render(args.geometry)
    if args.check:
        if not args.output.exists() or args.output.read_text() != expected:
            raise SystemExit("Firmware geometry is stale; run make_geometry.py then rebuild/rebind the UF2 assets")
        print("PASS: firmware count limits match canonical mechanical geometry")
    else:
        args.output.write_text(expected)
        print(args.output)
