#include <Arduino.h>
#include <esp_system.h>
#include <Arduino_GFX_Library.h>
#include <lvgl.h>
#include <Preferences.h>
#include <Wire.h>
#include "axs5106l.h"
#include "fw_version.h"

// Seed logos (172x320 full-bleed center crop, generated by
// tools/png_to_rgb565.py from images/flavor_N.png)
#include "images/flavor0_faucet.h"
#include "images/flavor1_faucet.h"

// ════════════════════════════════════════════════════════════
//  ESP32-S3 Faucet Display — Soda Flavor Selector
// ════════════════════════════════════════════════════════════
//
// Waveshare ESP32-S3-Touch-LCD-1.47 (172x320 IPS, JD9853 panel,
// AXS5106L capacitive touch) mounted on the gooseneck dispense head.
// The selected flavor's logo fills the screen; a tap anywhere toggles
// it. The selection persists in NVS across power cycles.
//
// Flavor state lives here for now. The UART/TinyProto link to the
// base ESP32 (state sync, flavor names/artwork push) plugs into
// setFlavor() and loop() — see the seam comments there.

// ── Theme (matches config display / iOS app) ──
#define THEME_BG  lv_color_hex(0x1a1a2e)

// ── Flavors ──
static const char *FLAVOR_NAMES[2] = {"Flavor 1", "Flavor 2"};
static const uint16_t *FLAVOR_BITMAPS[2] = {flavor0_faucet, flavor1_faucet};
static lv_img_dsc_t flavorLogos[2];

static uint8_t activeFlavor = 0;
static Preferences prefs;

// Persist is debounced off the tap path: NVS writes go to flash (and
// occasionally trigger page GC), so the tap handler only marks dirty.
static bool flavorDirty = false;
static unsigned long flavorChangedAt = 0;
#define FLAVOR_PERSIST_DELAY_MS 2000

// ── Diagnostics (read via GET_DIAG) ──
static uint32_t maxLoopMs = 0;
static uint32_t toggleCount = 0;

// ── Backlight / idle dimming ──
// Full brightness while in use; fades to a glanceable dim level after
// DIM_TIMEOUT_MS without input. While dimmed, the first tap only wakes
// the screen (consumed in onTap); serial flavor commands wake and apply.
#define BL_FULL_DUTY   255
#define BL_DIM_DUTY    8    // idle glow — soft but clearly visible in a dark room; 0 is off
#define BL_FADE_STEP   4    // duty per loop pass; fade spans (FULL-DIM)/STEP passes
#define DIM_TIMEOUT_MS 60000

static uint8_t blDuty = BL_FULL_DUTY;
static uint8_t blTarget = BL_FULL_DUTY;
static bool dimmed = false;
static unsigned long lastInputTime = 0;

// ── Pin assignments (fixed by Waveshare ESP32-S3-Touch-LCD-1.47) ──

// Display SPI (JD9853, 172x320, driven via the ST7789 command set)
#define LCD_DC    45
#define LCD_CS    21
#define LCD_SCK   38
#define LCD_MOSI  39
#define LCD_RST   40
#define LCD_BL    46

// Touch (AXS5106L)
#define TOUCH_SDA 42
#define TOUCH_SCL 41
#define TOUCH_RST 47
#define TOUCH_INT 48

#define SCREEN_W  172
#define SCREEN_H  320
#define ROTATION  2  // USB connector points up on the faucet mount

// ── Hardware objects ──
Arduino_DataBus *bus = new Arduino_ESP32SPI(
    LCD_DC, LCD_CS, LCD_SCK, LCD_MOSI, GFX_NOT_DEFINED, FSPI, true);

// The JD9853 speaks the ST7789 command set for addressing; panel-specific
// registers are programmed in lcdRegInit() after begin().
Arduino_GFX *gfx = new Arduino_ST7789(
    bus, LCD_RST, 0 /* rotation */, false /* IPS */,
    SCREEN_W, SCREEN_H,
    34 /* col offset 1 */, 0 /* row offset 1 */,
    34 /* col offset 2 */, 0 /* row offset 2 */);

AXS5106L touch(TOUCH_RST, TOUCH_INT);

// ── LVGL display buffer ──
static lv_disp_draw_buf_t draw_buf;
static lv_color_t *lvgl_buf;
#define LVGL_BUF_LINES 40

// ── UI objects ──
static lv_obj_t *logoImg;

// ════════════════════════════════════════════════════════════
//  JD9853 panel init (register sequence published by Waveshare)
// ════════════════════════════════════════════════════════════

static void lcdRegInit() {
  static const uint8_t init_operations[] = {
      BEGIN_WRITE,
      WRITE_COMMAND_8, 0x11,  // Sleep out
      END_WRITE,
      DELAY, 120,

      BEGIN_WRITE,
      WRITE_C8_D16, 0xDF, 0x98, 0x53,
      WRITE_C8_D8, 0xB2, 0x23,

      WRITE_COMMAND_8, 0xB7,
      WRITE_BYTES, 4,
      0x00, 0x47, 0x00, 0x6F,

      WRITE_COMMAND_8, 0xBB,
      WRITE_BYTES, 6,
      0x1C, 0x1A, 0x55, 0x73, 0x63, 0xF0,

      WRITE_C8_D16, 0xC0, 0x44, 0xA4,
      WRITE_C8_D8, 0xC1, 0x16,

      WRITE_COMMAND_8, 0xC3,
      WRITE_BYTES, 8,
      0x7D, 0x07, 0x14, 0x06, 0xCF, 0x71, 0x72, 0x77,

      WRITE_COMMAND_8, 0xC4,
      WRITE_BYTES, 12,
      0x00, 0x00, 0xA0, 0x79, 0x0B, 0x0A, 0x16, 0x79, 0x0B, 0x0A, 0x16, 0x82,

      WRITE_COMMAND_8, 0xC8,
      WRITE_BYTES, 32,
      0x3F, 0x32, 0x29, 0x29, 0x27, 0x2B, 0x27, 0x28, 0x28, 0x26, 0x25, 0x17,
      0x12, 0x0D, 0x04, 0x00, 0x3F, 0x32, 0x29, 0x29, 0x27, 0x2B, 0x27, 0x28,
      0x28, 0x26, 0x25, 0x17, 0x12, 0x0D, 0x04, 0x00,

      WRITE_COMMAND_8, 0xD0,
      WRITE_BYTES, 5,
      0x04, 0x06, 0x6B, 0x0F, 0x00,

      WRITE_C8_D16, 0xD7, 0x00, 0x30,
      WRITE_C8_D8, 0xE6, 0x14,
      WRITE_C8_D8, 0xDE, 0x01,

      WRITE_COMMAND_8, 0xB7,
      WRITE_BYTES, 5,
      0x03, 0x13, 0xEF, 0x35, 0x35,

      WRITE_COMMAND_8, 0xC1,
      WRITE_BYTES, 3,
      0x14, 0x15, 0xC0,

      WRITE_C8_D16, 0xC2, 0x06, 0x3A,
      WRITE_C8_D16, 0xC4, 0x72, 0x12,
      WRITE_C8_D8, 0xBE, 0x00,
      WRITE_C8_D8, 0xDE, 0x02,

      WRITE_COMMAND_8, 0xE5,
      WRITE_BYTES, 3,
      0x00, 0x02, 0x00,

      WRITE_COMMAND_8, 0xE5,
      WRITE_BYTES, 3,
      0x01, 0x02, 0x00,

      WRITE_C8_D8, 0xDE, 0x00,
      WRITE_C8_D8, 0x35, 0x00,  // Tearing effect on
      WRITE_C8_D8, 0x3A, 0x05,  // RGB565

      WRITE_COMMAND_8, 0x2A,
      WRITE_BYTES, 4,
      0x00, 0x22, 0x00, 0xCD,

      WRITE_COMMAND_8, 0x2B,
      WRITE_BYTES, 4,
      0x00, 0x00, 0x01, 0x3F,

      WRITE_C8_D8, 0xDE, 0x02,

      WRITE_COMMAND_8, 0xE5,
      WRITE_BYTES, 3,
      0x00, 0x02, 0x00,

      WRITE_C8_D8, 0xDE, 0x00,
      WRITE_C8_D8, 0x36, 0x00,  // MADCTL
      WRITE_COMMAND_8, 0x21,    // Inversion on
      END_WRITE,

      DELAY, 10,

      BEGIN_WRITE,
      WRITE_COMMAND_8, 0x29,  // Display on
      END_WRITE,
  };
  bus->batchOperation(init_operations, sizeof(init_operations));
}

// ════════════════════════════════════════════════════════════
//  LVGL callbacks
// ════════════════════════════════════════════════════════════

static void lvglFlush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p) {
  uint32_t w = area->x2 - area->x1 + 1;
  uint32_t h = area->y2 - area->y1 + 1;
  gfx->draw16bitRGBBitmap(area->x1, area->y1, (uint16_t *)&color_p->full, w, h);
  lv_disp_flush_ready(disp);
}

static void touchpadRead(lv_indev_drv_t *drv, lv_indev_data_t *data) {
  uint16_t x, y;
  if (touch.getTouch(&x, &y)) {
    lastInputTime = millis();
    data->point.x = x;
    data->point.y = y;
    data->state = LV_INDEV_STATE_PRESSED;
  } else {
    data->state = LV_INDEV_STATE_RELEASED;
  }
}

// ════════════════════════════════════════════════════════════
//  Flavor state
// ════════════════════════════════════════════════════════════

static void applyFlavorUi() {
  lv_img_set_src(logoImg, &flavorLogos[activeFlavor]);
}

static void wakeBacklight() {
  dimmed = false;
  blDuty = blTarget = BL_FULL_DUTY;
  ledcWrite(LCD_BL, blDuty);
  Serial.println("Backlight wake");
}

static void setFlavor(uint8_t f) {
  if (f > 1 || f == activeFlavor) return;
  lastInputTime = millis();
  if (dimmed) wakeBacklight();
  activeFlavor = f;
  applyFlavorUi();
  flavorDirty = true;
  flavorChangedAt = millis();
  toggleCount++;
  Serial.printf("Flavor -> %d (%s)\n", activeFlavor + 1, FLAVOR_NAMES[activeFlavor]);
  // Ecosystem seam: announce the change to the base ESP32 over UART here
  // (replaces the air-switch GPIO the ESP32 reads on the prototype).
}

static void onTap(lv_event_t *e) {
  if (dimmed) {  // a tap on a dimmed screen only wakes it
    lastInputTime = millis();
    wakeBacklight();
    return;
  }
  setFlavor(activeFlavor ^ 1);
}

// ════════════════════════════════════════════════════════════
//  UI
// ════════════════════════════════════════════════════════════

static void buildUi() {
  for (uint8_t i = 0; i < 2; i++) {
    flavorLogos[i].header.cf = LV_IMG_CF_TRUE_COLOR;
    flavorLogos[i].header.always_zero = 0;
    flavorLogos[i].header.w = SCREEN_W;
    flavorLogos[i].header.h = SCREEN_H;
    flavorLogos[i].data_size = SCREEN_W * SCREEN_H * sizeof(uint16_t);
    flavorLogos[i].data = (const uint8_t *)FLAVOR_BITMAPS[i];
  }

  lv_obj_t *scr = lv_scr_act();
  lv_obj_set_style_bg_color(scr, THEME_BG, 0);
  lv_obj_clear_flag(scr, LV_OBJ_FLAG_SCROLLABLE);

  // Flavor logo fills the panel
  logoImg = lv_img_create(scr);
  lv_obj_align(logoImg, LV_ALIGN_CENTER, 0, 0);

  // Full-screen tap target on top. Strip all theme styles — the theme's
  // pressed-state transition would otherwise animate this (invisible)
  // object on every tap, forcing extra full-screen redraws.
  lv_obj_t *overlay = lv_obj_create(scr);
  lv_obj_remove_style_all(overlay);
  lv_obj_set_size(overlay, LV_PCT(100), LV_PCT(100));
  lv_obj_clear_flag(overlay, LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_add_flag(overlay, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_add_event_cb(overlay, onTap, LV_EVENT_PRESSED, NULL);

  applyFlavorUi();
}

// ════════════════════════════════════════════════════════════
//  USB serial text commands (testing / diagnostics)
// ════════════════════════════════════════════════════════════

static void processTextLine(const char *line) {
  if (strcmp(line, "GET_VERSION") == 0) {
    Serial.printf("VERSION:FAUCET=%s\n", FW_VERSION);
  } else if (strcmp(line, "GET_STATE") == 0) {
    Serial.printf("STATE:FLAVOR=%d\n", activeFlavor);
  } else if (strcmp(line, "GET_DIAG") == 0) {
    Serial.printf("DIAG:heap=%lu,minHeap=%lu,touchInts=%lu,toggles=%lu,"
                  "maxLoopMs=%lu,dim=%d,bl=%u,uptime=%lus\n",
                  (unsigned long)ESP.getFreeHeap(),
                  (unsigned long)ESP.getMinFreeHeap(),
                  (unsigned long)touch.intCount(),
                  (unsigned long)toggleCount,
                  (unsigned long)maxLoopMs, dimmed ? 1 : 0, blDuty,
                  millis() / 1000);
    maxLoopMs = 0;  // high-water mark since last query
  } else if (strcmp(line, "TOGGLE") == 0) {
    setFlavor(activeFlavor ^ 1);
    Serial.printf("OK:FLAVOR=%d\n", activeFlavor);
  } else if (strncmp(line, "BL:", 3) == 0) {
    // Raw backlight poke (bring-up/demo). Holds until input or wake.
    if (line[3] < '0' || line[3] > '9' || atoi(line + 3) > 255) {
      Serial.println("ERR:BL expects 0-255");
    } else {
      int duty = atoi(line + 3);
      blDuty = blTarget = (uint8_t)duty;
      dimmed = duty < BL_FULL_DUTY;  // a tap on a poked-dim screen wakes, not toggles
      lastInputTime = millis();
      ledcWrite(LCD_BL, blDuty);
      Serial.printf("OK:BL=%d\n", duty);
    }
  } else if (strncmp(line, "FLAVOR:", 7) == 0) {
    uint8_t f = atoi(line + 7);
    if (f > 1) {
      Serial.println("ERR:FLAVOR out of range");
    } else {
      setFlavor(f);
      Serial.printf("OK:FLAVOR=%d\n", activeFlavor);
    }
  } else {
    Serial.printf("ERR:unknown command '%s'\n", line);
  }
}

// ════════════════════════════════════════════════════════════
//  Setup / loop
// ════════════════════════════════════════════════════════════

void setup() {
  Serial.begin(115200);
  // Never block on USB writes: the HWCDC TX buffer only drains while a host
  // is reading the port. With the default 100ms timeout, every print stalls
  // the loop once the buffer fills — felt as tap lag. 0 = drop instead.
  Serial.setTxTimeoutMs(0);
  delay(500);
  Serial.println("ESP32-S3 Faucet Display starting...");

  esp_reset_reason_t reason = esp_reset_reason();
  Serial.printf("Boot — firmware %s, heap=%lu, reset=%d\n",
                FW_VERSION, (unsigned long)ESP.getFreeHeap(), (int)reason);

  // Persisted flavor selection
  prefs.begin("faucet");
  activeFlavor = prefs.getUChar("flavor", 0);
  if (activeFlavor > 1) activeFlavor = 0;

  // Display hardware init
  if (!gfx->begin()) {
    Serial.println("gfx->begin() failed!");
  }
  lcdRegInit();
  gfx->setRotation(ROTATION);
  gfx->fillScreen(RGB565_BLACK);

  // Backlight on after the panel is initialized (avoids boot flash).
  // LEDC PWM so idle dimming can fade it.
  ledcAttach(LCD_BL, 5000, 8);
  ledcWrite(LCD_BL, blDuty);

  // Touch
  Wire.begin(TOUCH_SDA, TOUCH_SCL);
  touch.begin(Wire, ROTATION, gfx->width(), gfx->height());

  // LVGL init
  lv_init();
  lvgl_buf = (lv_color_t *)malloc(SCREEN_W * LVGL_BUF_LINES * sizeof(lv_color_t));
  if (!lvgl_buf) {
    Serial.println("FATAL: failed to allocate LVGL buffer!");
    while (1) delay(1000);
  }
  lv_disp_draw_buf_init(&draw_buf, lvgl_buf, NULL, SCREEN_W * LVGL_BUF_LINES);

  static lv_disp_drv_t disp_drv;
  lv_disp_drv_init(&disp_drv);
  disp_drv.hor_res = gfx->width();
  disp_drv.ver_res = gfx->height();
  disp_drv.flush_cb = lvglFlush;
  disp_drv.draw_buf = &draw_buf;
  lv_disp_drv_register(&disp_drv);

  static lv_indev_drv_t indev_drv;
  lv_indev_drv_init(&indev_drv);
  indev_drv.type = LV_INDEV_TYPE_POINTER;
  indev_drv.read_cb = touchpadRead;
  lv_indev_drv_register(&indev_drv);

  buildUi();

  lastInputTime = millis();
  Serial.printf("Ready — flavor %d (%s). Tap to switch.\n",
                activeFlavor + 1, FLAVOR_NAMES[activeFlavor]);
}

void loop() {
  unsigned long loopStart = millis();

  // USB serial commands (debug/test)
  static char usbBuf[64];
  static uint8_t usbPos = 0;
  while (Serial.available()) {
    char c = Serial.read();
    if (c == '\n' || c == '\r') {
      if (usbPos > 0) {
        usbBuf[usbPos] = '\0';
        processTextLine(usbBuf);
        usbPos = 0;
      }
    } else if (usbPos < sizeof(usbBuf) - 1) {
      usbBuf[usbPos++] = c;
    }
  }

  // Ecosystem seam: service the TinyProto link to the base ESP32 here.

  // Debounced flavor persist (off the tap path)
  if (flavorDirty && millis() - flavorChangedAt >= FLAVOR_PERSIST_DELAY_MS) {
    flavorDirty = false;
    prefs.putUChar("flavor", activeFlavor);
    Serial.printf("Persisted flavor %d\n", activeFlavor + 1);
  }

  // Idle dimming: set the dim target after inactivity, fade toward it.
  // Waking snaps to full (wakeBacklight), so the stepper only walks down.
  if (!dimmed && millis() - lastInputTime >= DIM_TIMEOUT_MS) {
    dimmed = true;
    blTarget = BL_DIM_DUTY;
    Serial.println("Backlight dim (idle)");
  }
  if (blDuty != blTarget) {
    int next = (int)blDuty - BL_FADE_STEP;
    if (next < (int)blTarget) next = blTarget;
    blDuty = (uint8_t)next;
    ledcWrite(LCD_BL, blDuty);
  }

  lv_timer_handler();

  unsigned long loopMs = millis() - loopStart;
  if (loopMs > maxLoopMs) maxLoopMs = loopMs;

  delay(5);
}
