// Batch rebuild of every CAD generator in dependency order — producers before
// the assemblies that load their STEPs — then every PCB board (its own bun
// pipeline, render-board.ts). The live watcher (server.js) keeps things fresh
// during editing, but only while it is running and only from the edit forward;
// a part changed while the watcher was down (or by a tool that doesn't trigger
// it) leaves its STEP-load consumers — or a board's committed views — silently
// stale. This walks the whole graph so the tree is self-consistent again.
//
//   node dev-server/build-all.js          rebuild everything, producers first
//   node dev-server/build-all.js --list   print the order, build nothing
//   node dev-server/build-all.js --check  rebuild, then exit 1 if any output
//                                         changed (CI: fail when something was
//                                         committed stale). Leaves the corrected
//                                         outputs in the tree — commit them.
//
// --check is the guard that would have caught the week-long enclosure staleness.
//
// It runs every generator in the tree, each as its own CadQuery process, so it
// costs minutes; `--list` prints the count without building. The commit-time gate
// is .githooks/pre-commit, which keys each check to the files actually staged.
//
// STDOUT IS THE ANSWER AND NOTHING ELSE — what failed, what was stale, and a final
// line that stands alone as the verdict. The per-generator progress goes to stderr,
// where the generators' own tracebacks already land. A run that finds nothing says
// so in one line, so there is no transcript here to filter and no reason for a
// caller to pipe this anywhere: whatever reads stdout gets the whole answer, and
// the exit code survives to mean what it says.

import fs from "fs";
import path from "path";
import { spawn, execFileSync } from "child_process";
import { fileURLToPath } from "url";

import { contentRoots, buildOrder } from "./deps.js";
import { walkPcbBoards } from "../lib/walk.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, "../..");
const PYTHON_BIN = path.join(PROJECT_ROOT, "tools", "cad-venv", "bin", "python");
const ROOTS = contentRoots(PROJECT_ROOT);

const rel = (p) => path.relative(PROJECT_ROOT, p);

function run(script) {
  return new Promise((resolve) => {
    // stderr inherited so Python tracebacks surface; stdout suppressed (the
    // generators print diagnostic dimensions on every run).
    const proc = spawn(PYTHON_BIN, [script], {
      cwd: path.dirname(script),
      stdio: ["ignore", "ignore", "inherit"],
    });
    proc.on("close", (code) => resolve(code ?? 0));
    proc.on("error", () => resolve(1));
  });
}

// Doc-sync drivers that read the PLACED MACHINE. They are `_`-prefixed, which is how
// `isRunnableScript` tells a shared module from a generator, so the CAD graph above skips
// them — but they are runnable entry points and what they write is a tracked file under a
// content root, which is exactly what --check already guards. They run after the graph,
// because the figures they copy are read off the STEPs it builds.
//
// NAMED, NOT DISCOVERED, and the naming is the point. Twenty-five `_`-prefixed scripts
// import `docgen`, and most are the ledger chain — §7's masses feed the totals, the totals
// feed the machine-hours — so running them in any order but that one leaves a doc stale
// after a full run, which is a --check that reports the same file forever. The ones here
// write a single doc apiece off the machine and settle in one pass; the ledger chain is
// ordered by `.githooks/pre-commit`, which is where it already runs.
const DOC_SYNCS = ["hardware/printed-parts/enclosure/_enclosure_dimensions.py"];

function docSyncDrivers() {
  return DOC_SYNCS.map((p) => path.join(PROJECT_ROOT, p)).filter((p) => fs.existsSync(p));
}

// PCB boards are generated by their own bun pipeline (render-board.ts), not the
// CadQuery graph, so they get their own pass: every board source under a content
// root, run as `bun render-board.ts <board>.tsx` in the board's directory. The
// outputs (the three deterministic copper view SVGs/PNGs + gerbers) land in
// out/, under the content roots, so --check's dirtyOutputs already guards them.
function pcbBoards() {
  const boards = [];
  for (const root of ROOTS) {
    for (const b of walkPcbBoards(root)) {
      boards.push({ dir: path.join(root, path.dirname(b.source)), file: path.basename(b.source) });
    }
  }
  return boards;
}

function runBoard(board) {
  return new Promise((resolve) => {
    const proc = spawn("bun", ["render-board.ts", board.file], {
      cwd: board.dir,
      stdio: ["ignore", "ignore", "inherit"],
      env: { ...process.env, RENDER_SOURCE: "build-all" },
    });
    proc.on("close", (code) => resolve(code ?? 0));
    proc.on("error", () => resolve(1));
  });
}

// Read-only: tracked outputs under the content roots that currently differ from
// HEAD. Used by --check to tell "this run made it dirty" (stale) from "it was
// already dirty" (someone's in-flight work).
function dirtyOutputs() {
  try {
    const out = execFileSync("git", ["status", "--porcelain", "--", ...ROOTS], {
      cwd: PROJECT_ROOT,
      encoding: "utf-8",
    });
    return out
      .split("\n")
      .filter((l) => l.trim())
      .map((l) => l.slice(3));
  } catch {
    return [];
  }
}

async function main() {
  const mode = process.argv[2];
  const order = buildOrder(ROOTS);
  const boards = pcbBoards();
  const syncs = docSyncDrivers();

  if (mode === "--list") {
    for (const s of order) console.log(rel(s));
    for (const b of boards) console.log(`${rel(path.join(b.dir, b.file))} (bun render-board.ts)`);
    for (const s of syncs) console.log(`${rel(s)} (doc-sync)`);
    console.log(`\n${order.length} generators (producers first) + ${boards.length} PCB boards`
                + ` + ${syncs.length} doc-sync.`);
    return;
  }

  const before = mode === "--check" ? new Set(dirtyOutputs()) : null;

  const failed = [];
  // Progress on stderr, beside the tracebacks it explains: a line that only says a
  // step is under way is stale the moment the next one starts, and stdout is
  // reserved for what is still true when the run ends.
  const step = (label, name) => process.stderr.write(`[${label}] ${name} ... `);
  const done = (code, name) => {
    process.stderr.write(code === 0 ? "ok\n" : `FAILED (${code})\n`);
    if (code !== 0) failed.push(name);
  };

  for (let i = 0; i < order.length; i++) {
    const name = rel(order[i]);
    step(`${i + 1}/${order.length}`, name);
    done(await run(order[i]), name);
  }
  for (let i = 0; i < boards.length; i++) {
    const b = boards[i];
    const name = rel(path.join(b.dir, b.file));
    step(`board ${i + 1}/${boards.length}`, name);
    done(await runBoard(b), name);
  }
  for (let i = 0; i < syncs.length; i++) {
    const name = rel(syncs[i]);
    step(`doc-sync ${i + 1}/${syncs.length}`, name);
    done(await run(syncs[i]), name);
  }
  const total = order.length + boards.length + syncs.length;

  if (failed.length > 0) {
    console.log(`${failed.length} of ${total} failed to build (traceback on stderr):`);
    for (const f of failed) console.log(`  ${f}`);
  }

  const stale = mode === "--check" ? dirtyOutputs().filter((f) => !before.has(f)) : [];
  if (stale.length > 0) {
    console.log(`${stale.length} output(s) were stale, regenerated in the tree — commit them:`);
    for (const f of stale) console.log(`  ${f}`);
  }

  // The last line is the whole verdict on its own, so a caller who reads nothing
  // else still reads the truth.
  const verdict = [
    failed.length > 0 ? `${failed.length} failed` : null,
    mode === "--check" ? (stale.length > 0 ? `${stale.length} stale` : "nothing stale") : null,
  ].filter(Boolean);
  console.log(`${total} run, ${verdict.length ? verdict.join(", ") : "0 failed"}.`);

  if (failed.length > 0 || stale.length > 0) process.exit(1);
}

main();
