#!/usr/bin/env python3
"""Render the Home Soda Machine identity from brand/mark.svg and brand/palette.json.

    tools/cad-venv/bin/python tools/build_brand_assets.py

SVG, PNG, Android VectorDrawable, PCB polylines and enclosure animation share
the same source geometry. Flavor images are independent of the brand artwork.
"""

from __future__ import annotations

import argparse
import io
import json
from pathlib import Path
import xml.etree.ElementTree as ET

import cairosvg
from fontTools.pens.recordingPen import RecordingPen
from fontTools.svgLib.path import parse_path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
BRAND = ROOT / "brand"
PUBLIC = ROOT / "web/public/brand"
PALETTE = json.loads((BRAND / "palette.json").read_text())
NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", NS)


def source():
    return ET.parse(BRAND / "mark.svg").getroot()


def geometry():
    root = source()
    faucet = root.find(f"{{{NS}}}path")
    drop = root.find(f"{{{NS}}}circle")
    return {"viewBox": [0, 0, 1024, 1024], "faucet": faucet.attrib["d"],
            "drop": {k: float(drop.attrib[k]) for k in ("cx", "cy", "r")}}


def svg(*, background=None, radius=0, scale=1, faucet=None, drop=None,
        drop_offset=0, drop_growth=0):
    root = source()
    path = root.find(f"{{{NS}}}path")
    circle = root.find(f"{{{NS}}}circle")
    if faucet:
        path.set("fill", faucet)
    if drop:
        circle.set("fill", drop)
    circle.set("cy", f'{float(circle.attrib["cy"]) + drop_offset:g}')
    circle.set("r", f'{float(circle.attrib["r"]) + drop_growth:g}')
    if scale != 1:
        group = ET.Element(f"{{{NS}}}g", {
            "transform": f"translate(512 512) scale({scale}) translate(-512 -512)"})
        for element in (path, circle):
            root.remove(element)
            group.append(element)
        root.append(group)
    if background:
        root.insert(1, ET.Element(f"{{{NS}}}rect", {
            "width": "1024", "height": "1024", "rx": str(radius), "fill": background}))
    return ET.tostring(root, encoding="unicode") + "\n"


def write(path, content):
    path = ROOT / path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def render(svg_text, size=1024, opaque=False):
    png = cairosvg.svg2png(bytestring=svg_text.encode(), output_width=size, output_height=size)
    image = Image.open(io.BytesIO(png)).convert("RGBA")
    return image.convert("RGB") if opaque else image


def png(path, svg_text, size, opaque=False):
    path = ROOT / path
    path.parent.mkdir(parents=True, exist_ok=True)
    render(svg_text, size, opaque).save(path, optimize=True)


def android_vector(scale):
    g = geometry()
    d = g["drop"]
    cx, cy, r = d["cx"], d["cy"], d["r"]
    circle = f"M{cx-r:g},{cy:g} a{r:g},{r:g} 0 1,0 {2*r:g},0 a{r:g},{r:g} 0 1,0 {-2*r:g},0 Z"
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/build_brand_assets.py from brand/mark.svg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="288dp" android:height="288dp"
    android:viewportWidth="1024" android:viewportHeight="1024">
    <group android:pivotX="512" android:pivotY="512"
        android:scaleX="{scale}" android:scaleY="{scale}">
        <path android:fillColor="{PALETTE['ice']}" android:pathData="{g['faucet']}"/>
        <path android:fillColor="{PALETTE['orange']}" android:pathData="{circle}"/>
    </group>
</vector>
'''


def flattened_faucet():
    pen = RecordingPen()
    parse_path(geometry()["faucet"], pen)
    points = []
    for op, args in pen.value:
        if op in ("moveTo", "lineTo"):
            points.append(args[0])
        elif op == "curveTo":
            p0, p1, p2, p3 = points[-1], *args
            for n in range(1, 17):
                t = n / 16
                u = 1 - t
                points.append(tuple(u**3*p0[j] + 3*u*u*t*p1[j] + 3*u*t*t*p2[j] + t**3*p3[j]
                                    for j in (0, 1)))
        elif op == "closePath":
            points.append(points[0])
        else:
            raise ValueError(f"Unsupported mark path command: {op}")
    return [[round(x, 4), round(y, 4)] for x, y in points]


def wordmark(stacked=False, reverse=False):
    color = PALETTE["ice"] if reverse else PALETTE["cobalt"]
    text_color = PALETTE["ice"] if reverse else PALETTE["navy"]
    inner = source()
    inner.find(f"{{{NS}}}path").set("fill", color)
    contents = "".join(ET.tostring(e, encoding="unicode") for e in inner if not e.tag.endswith("title"))
    letters = ET.parse(BRAND / "wordmark-lettering.svg").getroot().findall(f"{{{NS}}}path")
    text = []
    if stacked:
        dims = "0 0 1024 1000"
        mark = f'<g transform="translate(192 -56) scale(.625)">{contents}</g>'
        positions = [(512 - float(p.attrib["data-width"]) / 2, y) for p, y in zip(letters, (700, 848))]
    else:
        dims = "0 0 1680 640"
        mark = f'<g transform="translate(0 0) scale(.625)">{contents}</g>'
        positions = [(662, 300), (662, 475)]
    for path, (x, y) in zip(letters, positions):
        text.append(f'<path d="{path.attrib["d"]}" transform="translate({x:g} {y:g})"/>')
    return f'''<svg xmlns="{NS}" viewBox="{dims}" role="img" aria-label="Home Soda Machine">
{mark}
<g fill="{text_color}">{''.join(text)}</g>
</svg>\n'''


def build():
    PUBLIC.mkdir(parents=True, exist_ok=True)
    icon = svg(background=PALETTE["cobalt"])
    rounded = svg(background=PALETTE["cobalt"], radius=192)
    circle = svg(background=PALETTE["cobalt"], scale=.84)
    outputs = {
        "mark.svg": svg(), "mark-blue.svg": svg(faucet=PALETTE["cobalt"]),
        "mark-mono.svg": svg(faucet="currentColor", drop="currentColor"),
        "mark-white.svg": svg(faucet=PALETTE["white"], drop=PALETTE["white"]),
        "icon.svg": rounded, "icon-square.svg": icon,
        "wordmark.svg": wordmark(), "wordmark-stacked.svg": wordmark(stacked=True),
        "wordmark-reverse.svg": wordmark(reverse=True),
    }
    for name, artwork in outputs.items():
        write(PUBLIC / name, artwork)
    write(PUBLIC / "palette.json", json.dumps(PALETTE, indent=2) + "\n")
    write(PUBLIC / "geometry.json", json.dumps(geometry(), indent=2) + "\n")
    write("ios/AppIcon.svg", icon)
    assets = Path("ios/SodaMachine/SodaMachine/Assets.xcassets")
    png(assets / "AppIcon.appiconset/AppIcon.png", icon, 1024, opaque=True)
    png(assets / "LaunchIcon.imageset/LaunchIcon.png", svg(), 1024)
    color = PALETTE["cobalt"].lstrip("#")
    components = dict(zip(("red", "green", "blue"),
                          (f"0x{color[i:i+2]}" for i in (0, 2, 4))))
    components["alpha"] = "1.000"
    write(assets / "LaunchBackground.colorset/Contents.json", json.dumps({
        "colors": [{"color": {"color-space": "srgb", "components": components}, "idiom": "universal"}],
        "info": {"author": "xcode", "version": 1}}, indent=2) + "\n")
    res = Path("android/app/src/main/res")
    write(res / "drawable/launch_icon.xml", android_vector(0.70))
    write(res / "drawable/ic_launcher_foreground.xml", android_vector(0.66))
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        write(res / "mipmap-anydpi-v26" / name, '''<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/splash_bg"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
</adaptive-icon>
''')
    write(res / "values/colors.xml", f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated from brand/palette.json by tools/build_brand_assets.py. -->
<resources>
    <color name="splash_bg">{PALETTE['cobalt']}</color>
</resources>
''')
    pwa = Path("web/public/pwa-icons")
    for size in (192, 512):
        png(pwa / f"icon-{size}.png", icon, size, opaque=True)
    png(pwa / "icon-512-maskable.png", circle, 512, opaque=True)
    for size in (152, 167, 180):
        png(pwa / f"apple-touch-icon-{size}.png", icon, size, opaque=True)
    for size in (32, 64):
        png(pwa / f"favicon-{size}.png", rounded, size)
    png(PUBLIC / "icon-1024.png", rounded, 1024)
    png(PUBLIC / "avatar-1024.png", circle, 1024, opaque=True)
    png(PUBLIC / "mark-1024.png", svg(), 1024)
    png(PUBLIC / "mark-blue-1024.png", svg(faucet=PALETTE["cobalt"]), 1024)
    g = geometry()
    contour = flattened_faucet()
    d = g["drop"]
    data = {"faucet": contour, "drop": d,
            "bounds": {"left": min(min(x for x, y in contour), d["cx"] - d["r"]),
                       "top": min(min(y for x, y in contour), d["cy"] - d["r"]),
                       "right": max(max(x for x, y in contour), d["cx"] + d["r"]),
                       "bottom": max(max(y for x, y in contour), d["cy"] + d["r"])}}
    write("hardware/pcb/pcba/logo-geometry.ts",
          "/** Generated from brand/mark.svg by tools/build_brand_assets.py. */\n"
          + "export const logoGeometry = " + json.dumps(data, separators=(",", ":")) + " as const\n")
    print("Brand assets: web, PWA, iOS, Android, PCB geometry.")


def preview():
    board = Image.new("RGB", (1440, 1000), "#F3F6FF")
    draw = ImageDraw.Draw(board)
    font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 28)
    small = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 20)
    draw.text((64, 44), "Home Soda Machine  /  On tap", fill=PALETTE["navy"], font=font)
    art = render(svg(background=PALETTE["cobalt"], radius=192), 480)
    board.paste(art, (64, 125), art)
    blue = render(svg(faucet=PALETTE["cobalt"]), 360)
    board.paste(blue, (640, 125), blue)
    mono = render(svg(faucet=PALETTE["navy"], drop=PALETTE["navy"]), 256)
    board.paste(mono, (1070, 165), mono)
    draw.text((64, 645), "App icon", fill=PALETTE["navy"], font=small)
    draw.text((688, 530), "Full color mark", fill=PALETTE["navy"], font=small)
    draw.text((1100, 530), "One color", fill=PALETTE["navy"], font=small)
    x = 64
    for size in (180, 64, 48, 32, 16):
        art = render(svg(background=PALETTE["cobalt"], radius=192), size)
        board.paste(art, (x, 720), art)
        draw.text((x, 922), f"{size} px", fill=PALETTE["navy"], font=small)
        x += max(size + 40, 100)
    for i, (name, color) in enumerate(PALETTE.items()):
        x = 875 + i * 92
        draw.rounded_rectangle((x, 730, x + 68, 798), radius=10, fill=color)
        draw.text((x, 816), name, fill=PALETTE["navy"], font=small)
    board.save(BRAND / "preview.png", optimize=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--preview", action="store_true", help="Also render the reference sheet (macOS fonts).")
    args = parser.parse_args()
    build()
    if args.preview:
        preview()


if __name__ == "__main__":
    main()
