# Generate fw_version.h and, for the trees that ask for it, fw_build_time.h.
# Works for all environments — outputs to the correct source dir.
#
# THE TWO ARE SPLIT BECAUSE ONE OF THEM CHURNS. SCons rebuilds on content, so a
# header whose bytes move every build recompiles and relinks every translation
# unit that includes it — and the timestamp moves every second. FW_VERSION does
# not: it is a pure function of HEAD and whether the tree is dirty, so a build
# that changed nothing writes the same bytes and compiles nothing.
#
# A TREE GETS THE TIMESTAMP BY ASKING FOR IT. The header is written only where a
# source includes it, so nothing is generated into a tree that never reads it and
# the list cannot drift from what the code does.
Import("env")
import time
import os
import subprocess
import sys

timestamp = time.strftime("%b %d %Y %H:%M:%S")

# The source tree each environment builds, keyed by env name. Paths are
# relative to the project root, which is where PlatformIO runs this from.
# Every environment that names this script in extra_scripts is a key here.
SRC_DIR = {
    "appliance": "firmware/src_appliance",
    "prototype": "firmware/src_prototype",
    "rp2040_display": "firmware/src_display",
    "esp32s3_config": "firmware/src_config",
    "esp32s3_faucet": "firmware/src_faucet",
    "esp32s3_front": "firmware/src_front",
    "pcba_bench": "firmware/src_pcba_bench",
}

env_name = env["PIOENV"]
src_dir = SRC_DIR[env_name]
path = f"{src_dir}/fw_version.h"
build_time_path = f"{src_dir}/fw_build_time.h"

def fw_version():
    """The complete version string: HEAD's commit date (YYYY.MM.DD) and
    short SHA, with a trailing `+` when the working tree has uncommitted
    changes. Falls back to the build date + "unknown" when git is
    unavailable or this is not a repo.

    A clean version is a pure function of the commit — the date is the
    commit's own date, so it can never drift from the SHA it names — and a
    device reporting it pins the binary to exactly one source tree. A
    trailing `+` means it was built from that commit plus uncommitted edits,
    so the running code is the named commit "and then some" — likely the
    next commit, not the one listed. It is a clarification, not a warning:
    nothing is wrong. The generated fw_version.h files are gitignored, so a
    rebuild never adds a `+` on its own.
    """
    project_dir = env.subst("$PROJECT_DIR")

    def run(*args):
        return subprocess.run(
            ["git", *args], cwd=project_dir, capture_output=True, text=True
        )

    try:
        head = run("rev-parse", "--short", "HEAD")
        if head.returncode != 0:
            return time.strftime("%Y.%m.%d") + " unknown"
        rev = head.stdout.strip()
        commit_date = run(
            "show", "-s", "--format=%cd", "--date=format:%Y.%m.%d", "HEAD"
        )
        date = (
            commit_date.stdout.strip()
            if commit_date.returncode == 0
            else time.strftime("%Y.%m.%d")
        )
        status = run("status", "--porcelain")
        if status.returncode == 0 and status.stdout.strip():
            rev += "+"
        return f"{date} {rev}"
    except OSError:
        return time.strftime("%Y.%m.%d") + " unknown"


def write_if_moved(target, text):
    """Write `text` to `target` only when its bytes differ from what is there.

    An unconditional write is what SCons reads as a changed input, so a header
    rewritten with identical content still costs the recompile it describes.
    """
    try:
        with open(target, "r") as f:
            if f.read() == text:
                return
    except FileNotFoundError:
        pass
    with open(target, "w") as f:
        f.write(text)


def wants_build_time(directory):
    """Whether any source in this tree includes fw_build_time.h.

    The whole tree, because three of them keep sources a directory down.
    """
    for here, _dirs, names in os.walk(directory):
        for name in names:
            if not name.endswith((".cpp", ".h", ".c")):
                continue
            if name == "fw_build_time.h":
                continue
            with open(os.path.join(here, name), "r", errors="ignore") as f:
                if "fw_build_time.h" in f.read():
                    return True
    return False


write_if_moved(
    path,
    "// Auto-generated by pre_build.py — do not edit\n"
    f'#define FW_VERSION "{fw_version()}"\n',
)

if wants_build_time(src_dir):
    write_if_moved(
        build_time_path,
        "// Auto-generated by pre_build.py — do not edit\n"
        f'#define FW_BUILD_TIME "{timestamp}"\n',
    )
elif os.path.isfile(build_time_path):
    os.remove(build_time_path)

# ── Patch tinyproto library for PlatformIO compatibility ──
# TinyProtocol.cpp and TinySerialFdLink.cpp reference internal macros
# (FD_BUF_SIZE_EX) that fail to compile. We only need TinyProtocolFd,
# so remove the broken convenience wrappers from all environments.
# Also rename tiny_types.c → tiny_types.cpp so Arduino HAL functions
# (millis, delay) resolve correctly on the earlephilhower RP2040 core.
libdeps_dir = os.path.join(env.subst("$PROJECT_DIR"), ".pio", "libdeps", env_name, "Tiny Protocol", "src")
if os.path.isdir(libdeps_dir):
    for bad_file in [
        "TinyProtocol.cpp",
        os.path.join("link", "TinySerialFdLink.cpp"),
    ]:
        full = os.path.join(libdeps_dir, bad_file)
        if os.path.isfile(full):
            os.remove(full)

    # Rename .c → .cpp and inject #include <Arduino.h> so that
    # millis/delay/etc resolve on the RP2040 earlephilhower core.
    c_file = os.path.join(libdeps_dir, "hal", "tiny_types.c")
    cpp_file = os.path.join(libdeps_dir, "hal", "tiny_types.cpp")
    if os.path.isfile(c_file) and not os.path.isfile(cpp_file):
        os.rename(c_file, cpp_file)
    if os.path.isfile(cpp_file):
        with open(cpp_file, "r") as f:
            content = f.read()
        if "#include <Arduino.h>" not in content:
            content = '#include <Arduino.h>\n' + content
            with open(cpp_file, "w") as f:
                f.write(content)

    # Patch TinyProtocolFd.cpp: increase retry_timeout from 200ms to 2000ms
    # and retries from 2 to 4. The 200ms default is too aggressive — the main
    # loop can be blocked by LVGL/BLE/LittleFS, causing false disconnects.
    fd_cpp = os.path.join(libdeps_dir, "TinyProtocolFd.cpp")
    if os.path.isfile(fd_cpp):
        with open(fd_cpp, "r") as f:
            content = f.read()
        patched = False
        if "init.retry_timeout = 200;" in content:
            content = content.replace("init.retry_timeout = 200;", "init.retry_timeout = 2000;")
            patched = True
        if "init.retries = 2;" in content:
            content = content.replace("init.retries = 2;", "init.retries = 4;")
            patched = True
        if patched:
            with open(fd_cpp, "w") as f:
                f.write(content)

# ── The display art partitions ────────────────────────────────────────────
# Neither display compiles its pixels into its image any more; each has an
# `art` partition (firmware/partitions_s3_front.csv, firmware/partitions_s3.csv)
# and firmware/lib/board_art maps it. Laying the blob out here rather than by
# hand is what keeps it and the firmware from drifting: both come from this
# tree, in one build.
ART_BOARD = {"esp32s3_front": ("enclosure", "src_front"),
             "esp32s3_config": ("rotary", "src_config")}
if env_name in ART_BOARD:
    board, tree = ART_BOARD[env_name]
    art_out = os.path.join(env.subst("$BUILD_DIR"), "art.bin")
    maker = os.path.join(env.subst("$PROJECT_DIR"), "tools", "make_art.py")
    images = os.path.join(env.subst("$PROJECT_DIR"), "firmware", tree, "images")
    newest = max((os.path.getmtime(os.path.join(images, f))
                  for f in os.listdir(images) if f.endswith(".h")), default=0)
    if not os.path.isfile(art_out) or os.path.getmtime(art_out) < newest:
        os.makedirs(os.path.dirname(art_out), exist_ok=True)
        subprocess.run([sys.executable, maker, board, "-o", art_out, "-q"], check=True)
