# Generate fw_version.h with a build timestamp and git revision on every
# build. SCons uses content hashing, so we must change actual file content
# (not just mtime) to force recompilation of main.cpp.
# Works for all environments — outputs to the correct source dir.
Import("env")
import time
import os
import subprocess

timestamp = time.strftime("%b %d %Y %H:%M:%S")

# Determine output path based on environment. Paths are relative to
# the project root (PlatformIO runs pre_build.py from there), and the
# firmware source dirs live under firmware/ after the consolidation.
env_name = env["PIOENV"]
if env_name == "rp2040_display":
    path = "firmware/src_display/fw_version.h"
elif env_name == "esp32s3_config":
    path = "firmware/src_config/fw_version.h"
elif env_name == "esp32s3_faucet":
    path = "firmware/src_faucet/fw_version.h"
elif env_name == "esp32s3_front":
    path = "firmware/src_front/fw_version.h"
else:
    path = "firmware/src/fw_version.h"

def fw_version():
    """The complete version string: HEAD's commit date (YYYY.MM.DD) and
    short SHA, with a `-dirty` suffix when the working tree has uncommitted
    changes. Falls back to the build date + "unknown" when git is
    unavailable or this is not a repo.

    A clean version is a pure function of the commit — the date is the
    commit's own date, so it can never drift from the SHA it names — and a
    device reporting it pins the binary to exactly one source tree.
    `-dirty` means it was built from that commit plus uncommitted edits and
    so corresponds to no commit. The generated fw_version.h files are
    gitignored, so a rebuild never makes the tree look dirty on its own.
    """
    project_dir = env.subst("$PROJECT_DIR")

    def run(*args):
        return subprocess.run(
            ["git", *args], cwd=project_dir, capture_output=True, text=True
        )

    try:
        head = run("rev-parse", "--short", "HEAD")
        if head.returncode != 0:
            return time.strftime("%Y.%m.%d") + " unknown"
        rev = head.stdout.strip()
        commit_date = run(
            "show", "-s", "--format=%cd", "--date=format:%Y.%m.%d", "HEAD"
        )
        date = (
            commit_date.stdout.strip()
            if commit_date.returncode == 0
            else time.strftime("%Y.%m.%d")
        )
        status = run("status", "--porcelain")
        if status.returncode == 0 and status.stdout.strip():
            rev += "-dirty"
        return f"{date} {rev}"
    except OSError:
        return time.strftime("%Y.%m.%d") + " unknown"


header = (
    "// Auto-generated by pre_build.py — do not edit\n"
    f'#define FW_BUILD_TIME "{timestamp}"\n'
    f'#define FW_VERSION "{fw_version()}"\n'
)

try:
    with open(path, "r") as f:
        existing = f.read()
except FileNotFoundError:
    existing = ""

if existing != header:
    with open(path, "w") as f:
        f.write(header)

# ── Patch tinyproto library for PlatformIO compatibility ──
# TinyProtocol.cpp and TinySerialFdLink.cpp reference internal macros
# (FD_BUF_SIZE_EX) that fail to compile. We only need TinyProtocolFd,
# so remove the broken convenience wrappers from all environments.
# Also rename tiny_types.c → tiny_types.cpp so Arduino HAL functions
# (millis, delay) resolve correctly on the earlephilhower RP2040 core.
libdeps_dir = os.path.join(env.subst("$PROJECT_DIR"), ".pio", "libdeps", env_name, "Tiny Protocol", "src")
if os.path.isdir(libdeps_dir):
    for bad_file in [
        "TinyProtocol.cpp",
        os.path.join("link", "TinySerialFdLink.cpp"),
    ]:
        full = os.path.join(libdeps_dir, bad_file)
        if os.path.isfile(full):
            os.remove(full)

    # Rename .c → .cpp and inject #include <Arduino.h> so that
    # millis/delay/etc resolve on the RP2040 earlephilhower core.
    c_file = os.path.join(libdeps_dir, "hal", "tiny_types.c")
    cpp_file = os.path.join(libdeps_dir, "hal", "tiny_types.cpp")
    if os.path.isfile(c_file) and not os.path.isfile(cpp_file):
        os.rename(c_file, cpp_file)
    if os.path.isfile(cpp_file):
        with open(cpp_file, "r") as f:
            content = f.read()
        if "#include <Arduino.h>" not in content:
            content = '#include <Arduino.h>\n' + content
            with open(cpp_file, "w") as f:
                f.write(content)

    # Patch TinyProtocolFd.cpp: increase retry_timeout from 200ms to 2000ms
    # and retries from 2 to 4. The 200ms default is too aggressive — the main
    # loop can be blocked by LVGL/BLE/LittleFS, causing false disconnects.
    fd_cpp = os.path.join(libdeps_dir, "TinyProtocolFd.cpp")
    if os.path.isfile(fd_cpp):
        with open(fd_cpp, "r") as f:
            content = f.read()
        patched = False
        if "init.retry_timeout = 200;" in content:
            content = content.replace("init.retry_timeout = 200;", "init.retry_timeout = 2000;")
            patched = True
        if "init.retries = 2;" in content:
            content = content.replace("init.retries = 2;", "init.retries = 4;")
            patched = True
        if patched:
            with open(fd_cpp, "w") as f:
                f.write(content)
